#!/usr/bin/env bash
# Script that installs Nginx server, redirects /redirect_me and customizes 404 not found
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo sed -i '38i\error_page 404 /error_404.html;' /etc/nginx/sites-available/default
sudo service nginx start
