#!/usr/bin/env bash
# This script displays "bad luck from China" on loop 4.
# "bad luck from Japan" on loop 9.
# "bad luck from Italy on loop 17.
# Also displays a counter from 1 to 20 on every line.

i=1
while [ "$i" -le 20 ]
do
    echo "$i"
    case $i in
	4) echo "bad luck from China" ;;
	9) echo "bad luck from Japan" ;;
	17) echo "bad luck from Italy" ;;
    esac
    (( i++ ))
done
